### ISSUE TITLE
Split `Sql` in API

### ISSUE THREAD

**Issue by domartynov** [zio/zio-jdbc#101]
I think we need to rework API. A few thoughts:
* `zio.jdbc.{update, insert, delete}` are a bit confusing and have poor discoverability
* We can split `Sql` into: `SqlFragment` (without decoder), `Query` and maybe `Update`
* `SqlFragment` to define SQL and `PrepareStatement` parameters, with method e.g. `.execute`, `.query`, `.update`, `.updateWithGeneratedKeys`, etc
* `Query` to define the result set decoder with methods like e.g. `.selectAll`, `.selectOne`, `.selectStream`
* `Update` with `.execute: ZIO[ZConnection, Throwable, Long` and `.withGeneratedKeys: UpdateWithKeys[ZResultSet]`
So code looks more like:
```scala
sql"drop table foo".execute
sql"select * from foo".query[Foo].selectAll
sql"insert into foo".values(foo).updateWithGenerated.selectAll
```
I guess it can help to port code from `doobie` as well 🤔

**Comment by grouzen** [comment]
I'm already working on this one!
