### ISSUE TITLE
Close PreparedStatement when no longer needed

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-jdbc#138]
Currently there is no PreparedStatement re-using or pooling, so we have to close each one after we are done with it. That is not being done, which is a potential source of leaks.

A test suite should be added to ensure prepared statements are closed in a variety of scenarios (normal / errorful), as well as a fix for closing.

**Comment by FVelasquezM** [comment]
Currently working on this.
/attempt #138

**Comment by FVelasquezM** [comment]
I think the closing was already implemented by @adamgfraser in ZConnection's executeSqlWith function.

https://github.com/zio/zio-jdbc/blob/9a71ecb0c9a974cea504feb9de11c03c4d2f2bea/core/src/main/scala/zio/jdbc/ZConnection.scala#L39-L80

If I understand correctly the ZIO.acquireRelease should close the PrepareStatement after its done executing, could you confirm this?

**Comment by jdegoes** [comment]
Yes, that's correct. Please make a test suite if you'd like to finish this ticket!

**Comment by FVelasquezM** [comment]
Alright! Working on it, hope to update tomorrow!
