### ISSUE TITLE
sql interpolator bug: order is wrong with interpolated value at index 0

### ISSUE THREAD

**Issue by oyvindberg** [zio/zio-jdbc#172]
discovered in https://github.com/oyvindberg/typo/pull/57

```scala
    val s1 = sql"${"1"}::varchar".segments
    val s2 = (sql"${"1"}" ++ sql"::varchar").segments
    println(s1)
    println(s2)
```

prints:
```
Chunk(Syntax(::varchar),Param(1,zio.jdbc.SqlFragment$Setter$$anon$2@6a6afff2))
Chunk(Param(1,zio.jdbc.SqlFragment$Setter$$anon$2@6a6afff2),Syntax(::varchar))
```

Fairly sure the cause is the dropping of empty strings here:
https://github.com/zio/zio-jdbc/blob/main/core/src/main/scala/zio/jdbc/SqlInterpolator.scala#L32

in `s1` it drops the initial empty string, then consumes the second string, then consumes the interpolated value

**Comment by oyvindberg** [comment]
cc @guizmaii :)

**Comment by guizmaii** [comment]
@oyvindberg https://github.com/zio/zio-jdbc/pull/173 :)
