### ISSUE TITLE
sql interpolator adds empty Syntax at end of Chunk

### ISSUE THREAD

**Issue by yisraelU** [zio/zio-jdbc#22]
The interpolator yields an extra empty Syntax instance
```
  val ex1: Sql[ZResultSet]    = sql"select * from users where age = $age"
  println(ex1.segments)
Chunk(Syntax(select * from users where age = ),Param(42),Syntax())
```
If I understand correctly this is because parts of StringContext contains an extra empty string part if there are variables interpolated
https://www.scala-lang.org/api/2.12.2/scala/StringContext.html

**Comment by jdegoes** [comment]
We should fix this so that no "empty" syntaxes are added.

**Comment by yisraelU** [comment]
Ok .
I add pr
