### ISSUE TITLE
Save/restore stateful connection properties

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-jdbc#35]
**ISSUE**

With the usage of connections in a connection pool, we run into the following issue: a user may change a connection setting, and then upon the transaction being run, the connection will be returned to the pool, and the next client who commits a transaction will receive the "contaminated" connection with some stateful configuration that does not apply to the current connection.

**SOLUTION**

To deal with this situation, we should do two things:

1. When an initial connection is created for the very first time, we can "memorize" the values of stateful parameters on the `Connection`, and create a `restore` function (`Connection => Unit`) which can be used to restore stateful settings of a connection.
2. When a connection is returned to the pool, we can first restore it to its original state, by applying the `restore` function to the connection, which will ensure the next time the connection is retrieved from the pool, it looks like a 'fresh' connection.

**IMPACT**

Making this change to ZIO JDBC will ensure that the implementation detail of pooling connections (for performance reasons) does not "leak" into the application, breaking user expectations and causing apps to behave non-deterministically.

**WHERE TO LOOK**

 - [ZConnectionPool](https://github.com/zio/zio-jdbc/blob/main/core/src/main/scala/zio/jdbc/ZConnectionPool.scala#L157)
 - Javadoc for [Connection](https://docs.oracle.com/javase/7/docs/api/java/sql/Connection.html)
 - [resetConnectionState](https://github.com/brettwooldridge/HikariCP/blob/902fcf84a243124f2fc04702301e1a65e260b38b/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L205) in HikariCP

**PROBLEMMATIC ISSUES**

For maximum efficiency, only "dirty" settings would probably be restored, which would necessitate use of a proxy. An initial implementation, however, could ignore this optimization.

This improvement will help ensure that when we expose connection directly to users, they cannot inadvertently contaminate other transactions with transient changes to a connection.

**Comment by lukemcphee** [comment]
I can have a look at this

**Comment by masonedmison** [comment]
@jdegoes I'm a little late but I am going to take a stab at this. :)

**Comment by masonedmison** [comment]
@jdegoes I think I follow the problem and have a general idea on how to tackle this. The only thing I am not sure about is 
> When an initial connection is created for the very first time, we can "memorize" the values of stateful parameters on the `Connection`...

The only way I can think of to do this at the moment would be to add a check if the settings have been set as part of the `Connection` workflow (updating a `Ref` or something if they haven't been set). This doesn't seem right to me, as we would only ever want to set these values once and we would be performing this check on every `get` call from `ZPool` (or every time a resource is actually acquired from the pool). I could totally be off base here. Taking a quick look at HikariCP, it looks like these values are passed as configuration values.

**Comment by domartynov** [comment]
@jdegoes i think we still need to go with proxy objects like in HikariCP to detect the need to rollback a started transaction when the `autoCommit` mode is off. Although we can implement a version that always sends a rollback command as a part of restoring the state 🤔

**Comment by grouzen** [comment]
I came to the conclusion that we must finish this one before working on https://github.com/zio/zio-jdbc/issues/103 and https://github.com/zio/zio-jdbc/issues/77. I like the idea of implementing the Hikary approach with dirty bits.
