### ISSUE TITLE
Add a method to invalidate a connection to ZConnectionPool

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-jdbc#36]
Currently, we do not expose the capability to invalidate a connection in the connection pool. We could do this by exposing a `def invalidate(zc: ZConnection)` method directly in `ZConnectionPool`. Later, we can worry about automatically invalidating connections when certain criteria are met (e.g. a connection is possibly inadvertently closed).

**Comment by nhyne** [comment]
Hey I'd like to pick this one up as well if no one else has

**Comment by bluemontag** [comment]
Hi @jdegoes I would like to work on this one first, if anyone else is working on this, then I can take another

**Comment by nhyne** [comment]
@bluemontag I actually have a branch open for this, I haven't submitted the PR yet.

**Comment by bluemontag** [comment]
Hi @nhyne , please check and compare what I have done here: https://github.com/bluemontag/zio-jdbc/blob/main/core/src/main/scala/zio/jdbc/ZConnectionPool.scala

I have added the methods in the end of the file

**Comment by jdegoes** [comment]
@bluemontag This ticket is a bit simpler than what you imagine: it should not do any 'test', rather, it should simply force remove the connection from the pool, of course closing it if necessary before hand.

Only a simple: `ZConnectionPool#invalidate(connection)` is required for this one.

In separate pull request, we can do the validation that you have implemented here (#37). Maybe you could take on #37 after we get a fix for this one?

**Comment by bluemontag** [comment]
Yes @jdegoes , sure, let me take #37 instead, if this is simple and @nhyne has already on the path to solve it

**Comment by bluemontag** [comment]
Hi @jdegoes , I have created a PR with the validation to see if a connection is valid:

https://github.com/zio/zio-jdbc/pull/52/files

**Comment by masonedmison** [comment]
@jdegoes I believe this issue should be closed as #52 looks to have been merged.
