### ISSUE TITLE
Invalidate dead connections automatically

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-jdbc#37]
**ISSUE**

Currently there is no auto-invalidation for connections. This means that a "dead" connection can be returned to the connection pool, and sit there, waiting for the next request. This can potentially waste a lot of time, reducing application throughput.

Users would vastly prefer it if invalid / dead connections were detected and automatically removed from the pool, re-establishing fresh valid connections right away.

**SOLUTION**

After #36 is completed, we can check connections upon their return to the pool: and if a connection is closed or otherwise unusable, we can invalidate the connection automatically, so they can be refreshed by the connection pool.

**IMPACT**

Implementing this improvement will significantly increase application throughput in the presence of many closed or otherwise invalidated connections, and will result in a library that causes less confusion and troubleshooting for end-users.

**WHERE TO LOOK**

 - [ZConnectionPool](https://github.com/zio/zio-jdbc/blob/main/core/src/main/scala/zio/jdbc/ZConnectionPool.scala#L156)
 - `ZPool` (in ZIO 2.0)
 - [isConnectionDead](https://github.com/brettwooldridge/HikariCP/blob/902fcf84a243124f2fc04702301e1a65e260b38b/src/main/java/com/zaxxer/hikari/pool/PoolBase.java#L148) in HikariCP

**PROBLEMMATIC ISSUES**

While detecting if a connection is closed is simple, there are other ways a connection can be unusable, which should be investigated as part of this ticket.

**Comment by FVelasquezM** [comment]
Hi, new to ZIO and OSS in general, I'd like to take this one. 

Am I misunderstanding the scope or would this be solved simply by modifying a the `addFinalizerExit` of ZConnectionPool's make function in order to use invalidate a connection using ZPool's `invalidate` if it's invalid according to ZConnection's `isValid` method?
