### ISSUE TITLE
Automatically log all failed queries so the user doesn't have to log them manually

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-jdbc#4]
Failures can be logged via `ZIO.logErrorCause`.

**Comment by ASRagab** [comment]
@jdegoes I'd like to give this a try, is that okay?

**Comment by jdegoes** [comment]
Absolutely! Thanks for helping out.

**Comment by nhyne** [comment]
Hey I'm going to pick this one up if that's okay?

**Comment by ASRagab** [comment]
Yeah seems good...I would take a look at the comment history of the closed PR, might be instructive.
