### ISSUE TITLE
Release first version of ZIO JDBC

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-jdbc#50]
**ISSUE**

There have been no releases of ZIO JDBC, because the project has not been setup properly to release from tags on main.

**SOLUTION**

Using `sbt-releases` and associated Github Workflow machinery, it will be possible to make this project "auto-releasing", such that whenever a core ZIO JDBC contributor tags a new release on Github, the CI (Github CI) will build and release the project on Sonatype.

**IMPACT**

This improvement will make the release process extremely convenient for core ZIO JDBC developers, enabling them to focus on shipping new features and fixing bugs, rather than manually cutting releases on Sonatype. In addition, it will enable downstream usages of this library in ZIO SQL, ZIO Quill, and other libraries.

**WHERE TO LOOK**

Many existing libraries in the ZIO ecosystem have working release models, and can be used as the template for ZIO JDBC releases:

 - [ZIO Schema](https://github.com/zio/zio-schema)
 - [ZIO JSON](https://github.com/zio/zio-json)
 - [ZIO Core](https://github.com/zio/zio)

**PROBLEMATIC ISSUES**

It is possible that completing this ticket may require collaboration with ZIO core contributors, if any new secret keys need to be added to the ZIO organization.

**Comment by a-morales** [comment]
@jdegoes I've looked at this in order to be able to do https://github.com/zio/zio-sql/issues/664.

Looks like this project is already setup to do publishing as long as the following secrets are set: `PGP_PASSPHRASE`, `PGP_ SECRET`, `SONATYPE_PASSWORD`, `SONATYPE_USERNAME`. Once the secrets are set then a tag needs to be pushed to be able to publish. 

I'll make a PR to update this project to ZIO 2.0.0-RC6 then a publish can be attempted.

**Comment by domartynov** [comment]
@jdegoes @a-morales What the current state of the issue? Any blockers to make a release of the library? I'd like to contribute the project as the project fits my use case perfectly.

As I'd like to avoid "heavy" dependencies like `doobie` and `cats` in my project to implement the Outbox pattern specifically from Postgres to Kafka where I have only a few queries and need explicit control over the connection life-cycle (so don't need to use a conn pool even) to place a session-level lock needed for ordering and exactly-once delivery guarantees.
