### ISSUE TITLE
Question: Introduce polymorphic param and sql interpolator

### ISSUE THREAD

**Issue by yisraelU** [zio/zio-jdbc#51]
currently Param holds type Any and at the point of generating a Statement we check the type,
Should we 
A. introduce a type parameter to Param perhaps with an implicit of a type Encodable (we would need to create such a trait with implementations ) ?
B. change the interpolator to fail is the type passed in is not of type Encodable   ?

**Comment by jdegoes** [comment]
I am not sure there is a way to make string interpolation type-safe, because at the point where you have a `StringContext`, all the damage has already been done.

**Comment by yisraelU** [comment]
@jdegoes I was thinking of something like this
```
  implicit def decodableValue[A](a:A)(implicit ev: Decodable[A]): DecodableWithValue[A] =
    DecodableValue(a)
case class DecodableValue[A:Decodable](value: A)
```
and the interpolator would take in an existential like so 
```
def sql(params: DecodableWithValue[_]*):SqlFragment
```
this solves imposing a limit on the interpolator
