### ISSUE TITLE
Scala 3 support/release

### ISSUE THREAD

**Issue by kirillsalykin** [zio/zio-jdbc#75]
According to this https://search.maven.org/search?q=a:zio-jdbc_2.13 -  there is no Scala 3 support.

Please add Scala 3 support and make a release.

**Comment by jdegoes** [comment]
If someone volunteers to update the build, I will do a new release for Scala 3.

**Comment by wheatandtares** [comment]
I tested the PR referenced and it works for me in Scala 3.

**Comment by kirillsalykin** [comment]
@jdegoes could you please check the MR?
