### ISSUE TITLE
The automated lint process stops due to problems in project/BuildHelper.scala

### ISSUE THREAD

**Issue by karvanit** [zio/zio-jdbc#99]
This will cause every pull request to fail at some automated checks.

**Comment by lucasamoroso** [comment]
Hello! I looked into the issue you mentioned and it appears that it has already been resolved in [this](https://github.com/zio/zio-jdbc/commit/e57417d93fedb5e1f6199cec0bbbb6a2813b063d#diff-dd3701b993fcc974a9a6d017159aac00d4b41bcd05ad319815c6001311c669d5) PR . I tested this by checking out the commit 19e4fe4853c4d87f075e9ea32507051e16a3cdf6, which was before the fix, and running `sbt check`, which failed. However, when I checked out the last commit on BuildHelper.scala (e57417d93fedb5e1f6199cec0bbbb6a2813b063d), the `sbt check` command succeeded. You can see the output of these tests in these images: ![image](https://user-images.githubusercontent.com/18125567/236631906-ad162273-e7c7-4981-acd6-c76cc7c68a2d.png) and ![image](https://user-images.githubusercontent.com/18125567/236632201-354c88d5-e3ff-4e1b-a21c-fa25946c71c7.png). Therefore, it seems that the fix implemented in the commit resolved the issue.
